### PR TITLE
:recycle: Refactor Cloudinary upload logic to add a upload retry

### LINKED ISSUE #82: [Feature] Add retry logic for failed uploads
# **Feature Request**

## **Is your feature request related to a problem? Please describe.**

If an upload fails, we should attempt to re-upload.

Likely would only want to re-attempt that upload once.

### PR DESCRIPTION
**Pull request by kcoderhtml**
Hopefully this works :)

Fixes #82

### CODE REVIEW

**Comment by colbyfayock** [comment]
hey @kcoderhtml clever idea of using a loop like that, hadnt considered that

i think we're running into an issue though, where the retry logic doesn't seem to be running for me

to test, i replaced `fullPath` in both upload lines to something random and invalid like `/`

i think what's happening is that when the first error occurs, the catch re-throws the error, resulting in `getCloudinaryUrl` throwing the error and never hitting the second attempt, though i certainly may be wrong

i wasn't able to  get `console.log('attempt', attempt)` logged out more than once by placing it at the of the loop

i'm wondering if the loop needs to be inside of the try catch, or perhaps inside of the catch, you first check the attempt number and seeing if it's at the maximum number of attempts before throwing (which we could possibly set up for configuration later)

any chance you were able to get this running locally? if not and you're willing to try, happy to help you get set up if the instructions on the README didnt work, that way you can test it out

**Comment by kcoderhtml** [comment]
I would be happy to help but could not get the demo site to run, I kept getting this error: https://app.warp.dev/block/AK6xV3BiPb68w5XM3cyhh7.

**Comment by colbyfayock** [comment]
oh weird - is that after building the project? since it needs to compile the TS, otherwise the files wont exist in `dist` which is the output folder

**Comment by kcoderhtml** [comment]
I just tried building, but I got this error: https://app.warp.dev/block/ZpMZMoKUYbvYa2Zv1Qy24Y. I also tried with `npm run build` but it wanted me to install the node modules, but they wouldn't install: https://app.warp.dev/block/UV6d9X6VzdjyV49kvpYiSi. I'm sure I'm missing something, so thank you for your help.

**Comment by colbyfayock** [comment]
how about try the following

in the root:
```
pnpm install
pnpm build
```

then i usually test with this command:

```
netlify deploy --build --filter docs --context production
```

i run it directly instead of trying to use the package.json script

production might not be required but it helps point to images that are on the production site, and sometimes building locally can be problematic

im not sure if you set it up yet but it requires the Netlify CLI and logged in to an account

if you dont have any luck, i wonder if it's reproducible by adding a test for `getCloudinaryUrl` with it

**Comment by kcoderhtml** [comment]
The `pnpm build` fails with `You must supply a cloudName when initializing the asset`.

**Comment by colbyfayock** [comment]
yeah, you need to configure the cloud name in order for it to work as it ultimately uploads and uses Cloudinary, which requires an account

**Comment by colbyfayock** [comment]
@kcoderhtml were you going to continue on this? if this is wrapped up by mid-November we can still consider this Hackoberfest given it was opened within October

**Comment by kcoderhtml** [comment]
Sorry, I've been quite busy these last few weeks. I am still working on this and will be writing a test for the code piece.

**Comment by colbyfayock** [comment]
awesome sounds great! thank you, let me konw if you need a hand

**Comment by kcoderhtml** [comment]
thanks! will do.

**Comment by colbyfayock** [comment]
hey @kcoderhtml when you get back to this, please merge in `main` as it has some updates in the main `index.ts` related to concurrency. hoping it doesnt conflict with your work

PR: https://github.com/cloudinary-community/netlify-plugin-cloudinary/pull/89

**Comment by kcoderhtml** [comment]
I think that might have done it! There is a new timeout and maxRetries settings to adjust to your liking.

**Comment by colbyfayock** [comment]
awesome! the retries worked great

im seeing one issue though that makes me think there's a loose async request somewhere, but i can't tell if its your code or the wraping code

image

if you notice, the 3rd attempts are happening in a later build stage which i think could potentially cause issues if there's a lot of uploads

im goign to play around with it a little more likely next week to try to determine the cause of that, but this code genrally is looking great

**Comment by colbyfayock** [comment]
yeah its definitely related to this code somehow. i put a before/after console log around the async function and without the code, it all wraps up before continuing

image


but with the code, it never ends

image

everything looks sounds to me though, i wonder if something is happening 

the way im testing this btw is replacing `fullPath` with garbage `./asdf` and it fails automatically.

**Comment by colbyfayock** [comment]
i think i figured it out and i dont think its actually related to this - ithink the error that's being thrown from within getCloudinaryUrl is not being properly caught anymore from within the wrapping code and thats causing the issue. im gonna separately get a bug fix in

**Comment by colbyfayock** [comment]
apologies for the confusion there but we're good to go!

thanks @kcoderhtml great add here

**Comment by colbyfayock** [comment]
@all-contributors please add @kcoderhtml for code

**Comment by kcoderhtml** [comment]
Thank you! Will this be included in cloudinary hacktoberfest contributions? The swag pack looks pretty sweet!

**Comment by colbyfayock** [comment]
@kcoderhtml congrats on the merged PR! since you opened this in October, you've qualified for Hacktoberfest swag! please email [hacktoberfest@cloudinary.com](mailto:hacktoberfest@cloudinary.com) with your github username and a link to your contribution where I'll follow up to request more information for getting you your swag

https://cloudinary.com/blog/hacktoberfest-celebrate-open-source-sdks

**Comment by kcoderhtml** [comment]
Thank you!

**Pull request merged**
