### PR TITLE
Fixes Netlify URL

### LINKED ISSUE #83: [Bug] Host of deployed images is undefined when using fetch
# **Bug Report**

## **Describe the bug**

When using fetch, the netlify deployed URL is currently showing as undefined

## **Steps To Reproduce the error**

1.
2.
3.
4.

### **Your environment**

- OS: 
- Node version:
- Npm version:
- Browser name and version:

### PR DESCRIPTION
**Pull request by colbyfayock**
# Description

## Issue Ticket Number

Fixes #83 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist

- [ ] I have followed the contributing guidelines of this project as mentioned in [CONTRIBUTING.md](/CONTRIBUTING.md)
- [ ] I have created an [issue](https://github.com/colbyfayock/netlify-plugin-cloudinary/issues) ticket for this PR
- [ ] I have checked to ensure there aren't other open [Pull Requests](https://github.com/colbyfayock/netlify-plugin-cloudinary/pulls) for the same update/change?
- [ ] I have performed a self-review of my own code
- [ ] I have run tests locally to ensure they all pass
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes needed to the documentation

### CODE REVIEW

**Comment by JingshanDu** [comment]
When will this fix be live on Netlify? I don't see a Change Version option for the Cloudinary plugin like some others. I am unable to build my site today due to this URL issue and had to revert it to a previous deployment.

**Comment by colbyfayock** [comment]
hey @JingshanDu i'm hoping by tomorrow this will go out. it's already been reviewed by the Netlify team, just waiting for the actual deployment

https://github.com/netlify/plugins/pull/1257

i plan on following up with them tomorrow

**Comment by colbyfayock** [comment]
@JingshanDu good news, this is now deployed on netlify, so everything should be good to go, but please report an Issue if you run into anything

**Comment by JingshanDu** [comment]
@colbyfayock Thanks for the update! This version is working well and has resolved the issue.

**Pull request merged**
